app:
  id: universe-book-api-private
apollo:
  bootstrap:
    enabled: true #开启对默认命名空间application的识别
    namespaces: application #如果要同时拉取多个命名空间，中间以逗号分隔
    eagerLoad:
      enabled: true #针对Apollo的加载顺序放到日志系统加载之前，如果配置了日志内容，必须增加

spring:
  datasource:
    # 配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://new2.mysql.tuling.com:3306/turing_universe_book?characterEncoding=utf-8&autoReconnect=true
    username: appuser
    password: appuser123
    druid:
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          # 初始化大小,最小,最大
          initial-size: 5
          max-active: 50
          min-idle: 5
          # 配置获取连接等待超时时间
          max-wait: 60000
          # 打开PSCache，并且指定每个连接上PSCache的大小
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          validation-query: SELECT 'x'
          validation-query-timeout: 60000
          test-on-borrow: true
          test-on-return: true
          test-while-idle: true
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          log-abandoned: true
          remove-abandoned: true
          remove-abandoned-timeout: 1800
          filters: stat,wall

          web-stat-filter:
            enabled: true
            url-pattern: /*
            exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'

          # 管理后台的url和登录账号密码
          stat-view-servlet:
            enabled: true
            url-pattern: /druid/*
            reset-enable: true
            login-username: admin
            login-password: 123456

          # 配置StatFilter
          filter:
            stat:
              db-type: mysql
              log-slow-sql: true
              slow-sql-millis: 2000
            # 配置WallFilter
            wall:
              db-type: mysql
              enabled: true
              config:
                delete-allow: true
                drop-table-allow: false
                multi-statement-allow: true
                delete-where-alway-true-check: true
                delete-where-none-check: true
          # 合并多个DruidDataSource的监控数据
          use-global-data-source-stat: true
#mybatis-plus
#mybatis-plus:
#  mapper-locations: classpath:com/mht/springbootmybatisplus/mapper/xml/*.xml
#mybatis-plus:
#  type-aliases-package : com.turing.universe.entity
#
#mybatis-plus.configuration.map-underscore-to-camel-case: true
